---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: formatting.tex
geometry: margin=1in

title: "CV"
author: Hannah Rachel Nelson
#orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "Center for Population Biology · University of California, Davis"
address: "2320 Storer Hall, Davis, CA 95616"
fontawesome: yes
email: hrnelson@ucdavis.edu
github: hrnelson
#phone: "+1 555 5555"
web: 'hrnelson.com'
updated: no

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
# Education

*University of California, Davis*, Ph.D. student, Population Biology \hfill 2017-present

*California State University, Northridge*, M.S. Biology with distinction \hfill 2016

*Brown University*, B.S. Marine Biology with honors, *magna cum laude* \hfill 2014

*Northeastern University*, Three Seas Program \hfill 2012-2103

# Publications

Courtney TA, Barnes BB, Chollett I, Elahi R, Gross K, Guest JR, Kuffner IB, Lenz EA, **Nelson HR**, Rogers, CS, Toth LT, Andersson AJ. 2020. Disturbances drive changes in coral community assemblages and coral calcification capacity. *Ecosphere* 11(4):e03066. https://doi.org/10.1002/ecs2.3066

Altieri AH, **Nelson HR**, Gedan KB. 2019. The significance of ocean deoxygenation for tropical ecosystems-corals, seagrasses, and mangroves. In D. Laffoley & JM Baxter (Eds.), *Ocean Deoxygenation–Everyone's Problem: Causes, Impacts, Consequences and Solutions* (pp. 401-429). International Union for Conservation of Nature and Natural Resources. Gland, Switzerland. https://doi.org/10.2305/IUCN.CH.2019.13.en

**Nelson HR**, Altieri AH. 2019. Oxygen: the universal currency on coral reefs. *Coral Reefs* 38(2):177-198. https://doi.org/10.1007/s00338-019-01765-0

Edmunds PJ, **Nelson HR**, Bramanti L. 2018. Density-dependence mediates coral community structure. *Ecology* 99(11):2605-2613. https://doi.org/10.1002/ecy.2511

Guest JR, Edmunds PJ, Gates RD, Kuffner IB, Andersson AJ, Barnes BB, Chollett I, Courtney TA, Elahi R, Gross K, Lenz EA, Mitarai S, Mumby PJ, **Nelson HR**, Parker BA, Putnam HM, Rogers CS, Toth LT. A framework for identifying and characterising coral-reef “oases” against a backdrop of degradation. *Journal of Applied Ecology* 55(6):2865-2875. https://doi.org/10.1111/1365-2664.13179

**Nelson HR**, Kuempel CD, Altieri AH. 2016. The resilience of reef invertebrate biodiversity to coral mortality. *Ecosphere* 7(7):e01399. https://doi.org/10.1002/ecs2.1399

# Research Experience

*Research Assistant, University of California, Davis, Bodega Marine Laboratory* \hfill 2017-present

> Construction and deployment of seagrass field experiments, tank cleaning and maintenance, rocky shore algal and invertebrate surveys, and various other projects.

*Intern, Smithsonian Tropical Research Institute, Panama City, Panama* \hfill 2017

> Compiled and wrote literature review on the role of oxygen in the structure and dynamics of coral reefs.

*Research Assistant, California State University, Northridge, USA* \hfill 2014-2016

> Assisted with the St. John Long-Term Coral Reef Dynamics (NSF-LTREB) and Moorea Coral Reef Long-Term Ecological Research (NSF–LTER) projects through field support, mesocosm measurements and maintenance, and analysis of time series photographs.

*Intern, Smithsonian Tropical Research Institute, Bocas del Toro, Panama* \hfill 2013-2014

> Designed experiments and field surveys to examine resilience of invertebrate communities to coral reef hypoxia event. Also assisted with other reef, mangrove, and seagrass projects.

*NSF REU Program, Whitney Laboratory for Marine Bioscience, St. Augustine, FL, USA* \hfill 2012

> Examined the effects of multiple predators and prey-size preferences on Atlantic oyster populations through field surveys, laboratory feeding trails, and a mesocosm experiment.

*Research Assistant, Leslie Lab, Brown University, Providence, RI, USA, 2012* \hfill 2012

> Assisted Brown-MBL PhD student Sarah Corman process salt marsh core samples for her project entitled "Salt Marsh Responses to Climate Change Impacts."

# Funding

Center for Population Biology Research Award, University of California, Davis ($2244) \hfill 2020

Center for Population Biology Supplement for Citizen Science & Outreach Award, University of California, Davis ($500) \hfill 2020

Center for Population Biology Research Award, University of California, Davis ($700) \hfill 2019

Center for Population Biology Supplement for Citizen Science & Outreach Award, University of California, Davis ($350) \hfill 2019

XSEDE Startup Grant, National Science Foundation ($909.50) \hfill 2019

Graduate Student Association (GSA) Travel Award, University of California, Davis ($500) \hfill 2018

Student Travel & Academic Research (STAR), California State University, Northridge ($400) \hfill 2016

Student Travel Award, Council on Ocean Affairs, Science, & Technology (COAST) ($1000) \hfill 2016

Graduate Studies Travel Award, California State University, Northridge ($400) \hfill 2016

Thesis Support Award, California State University, Northridge ($1000) \hfill 2014

Brown International Scholars Program Award, Brown University ($5000) \hfill 2013

Undergraduate Teaching and Research Award, Brown University ($1500) \hfill 2011


# Academic Honors & Awards

Best Paper Award, Coral Reefs, Journal of the International Coral Reef Society \hfill 2019 

Golden Key International Honour Society, University of California, Davis \hfill 2018

Julie Gorchynski, M.D. Center for Cancer & Developmental Biology Graduate Research Award \hfill 2017

Honorable Mention, Best Student Presentation in Population & Organismal Biology, WSN Meeting \hfill 2015

Honorable Mention, NSF Graduate Research Fellowship Program \hfill 2015

2nd Place, Best Graduate Student Poster, CSUN Student Research & Creative Works Symposium \hfill 2015

Sigma Xi Honor Society, Brown University \hfill 2014

Phi Beta Kappa Honor Society, Brown University \hfill 2014

Finalist, Raymond B. Huey (DEE) Best Student Poster Presentation, SICB Meeting \hfill 2013

Dean's List, Spring 2013 Semester, Northeastern University \hfill 2013

Dean's List, Fall 2012 Semester, Northeastern University \hfill 2012

Best Poster Presentation, REU Program, UF Whitney Laboratory for Marine Bioscience \hfill 2012

# Presentations

\vspace{-2mm}
*\* oral presentation, $\dagger$ poster presentation, $^{\circ}$ co-presenter*, $\diamond$ invited speaker

**Nelson, HR**. 2020. From Trees to Octocorals: The Role of Phenotypic Integration in Underwater Animal Forests. *Biology Research Seminar Course (NSM90), California State University, Sacramento*. Sacramento, CA*$\diamond$

**Nelson HR**. 2020. STEM Outreach: Middle School. *Science Communication Tools for the Modern Era Course (ANB290), University of California, Davis*. Davis, CA*$\diamond$

**Nelson HR**. 2019. STEM Outreach: Middle School. *Science Outreach: How to Increase the Impact of Your Work Workshop, University of California, Davis*. Davis, CA*$\diamond$

**Nelson HR**. 2018. The evolution of coloniality in ascidians. *Population Biology Graduate Group Annual Student Symposium, University of California, Davis*. Davis, CA*

**Nelson HR**, Altieri AH. 2017. Coral reefs: Extreme oxygen environments? *Coastal & Estuarine Research Federation 24th Biennial Conference*. Providence, RI*

**Nelson HR**, Edmunds PJ. 2016. The role of density-associated processes and shading in the structure and distribution of octocoral communities. *97th Annual Western Society of Naturalists Meeting*. Monterey, CA*

**Nelson HR**, Edmunds PJ. 2016. Allometry and integration constrain Caribbean ocotocoral morphology. *13th International Coral Reef Symposium*. Honolulu, HI*

Sternberg DR, **Nelson HR**, Edmunds PJ. 2015. Asexual budding and aggregated spatial distribution of fungiid corals from disturbed reefs in Moorea, French Polynesia. *Moorea Coral Reef Long Term Ecological Research Site 11th Annual All Investigators Meeting*. Santa Barbara, CA*$^{\circ}$

**Nelson HR**, Edmunds PJ. 2015. Allometry and integration constrain Caribbean ocotocoral morphology. *96th Western Society of Naturalists Meeting*. Sacramento, CA*

**Nelson HR**, Altieri AH, Kuempel CD. 2015. Effects of coral mortality on reef invertebrate communities. *California State University, Northridge 19th Annual Student Research and Creative Works Symposium*. Northridge, CA$\dagger$

**Nelson HR**, Sternberg DR, and Edmunds PJ. 2015. Asexual budding and aggregated spatial distribution of fungiid corals from disturbed reefs in Moorea, French Polynesia. *9th Long Term Ecological Research All Scientists Meeting*. Estes Park, CO$\dagger$

**Nelson HR**, Altieri AH, Kuempel CD. 2014. Effects of coral mortality on reef invertebrate communities. *95th Annual Western Society of Naturalists Meeting*. Tacoma, WA$\dagger$

**Nelson HR**, Griffin J, McCoy M, Silliman B. 2013. Despite resource partition, multiple predators reduce mortality risk for foundation species. *Society for Integrative & Comparative Biology Annual Meeting*. San Francisco, CA$\dagger$

# Teaching Experience

Associate Instructor, Introductory Biology Co-Class, University of California, Davis \hfill Fall 2020

Instructor, BUSP Biology Boot Camp, University of California, Davis \hfill Summer 2020

Teaching Assistant, Introductory Biology Co-Class, University of California, Davis \hfill Spring 2020

Teaching Assistant, Marine Ecology, University of California, Davis \hfill Winter 2019

Teaching Assistant, BUSP Biology Boot Camp, University of California, Davis \hfill Summer 2019 

Teaching Assistant, Principles of Ecology and Evolution, University of California, Davis \hfill Fall 2018, 2019

Graduate Assistant, Biometry, California State University, Northridge \hfill Fall 2015, 2016

Peer Learning Facilitator, Evolutionary Biology, California State University, Northridge \hfill Fall 2016

Peer Learning Facilitator, Biological Principles, California State University, Northridge \hfill Fall 2015

# Professional Service

## **Academic Organizations**

Teaching Assistant Consulting Fellows, Center for Educational Effectiveness, University of California, Davis

> *Program Improvement Lead* (2020-present), *Graduate Teaching Fellow* (2019-present)

Graduate Teaching Community, Center for Educational Effectiveness, University of California, Davis

> *Facilitator* (2020-present)

Equity in Science, Technology, Engineering, Math, and Entrepreneurship, University of California, Davis

> *Vice President of Outreach* (2018-2019), *STEM Squad Coordinator* (2017-present)

Biology Alumni Association Board, California State University, Northridge

> *Student Liaison* (2016)

Women in Science Club, California State University, Northridge

> *President* (2015-2016), *Vice President* (2014-2015)

Marine Biology Graduate Student Association, California State University, Northridge

> *Vice President* (2014-2015)

## **Professional Membership**

Ecology Society of America

International Society for Reef Studies

Western Society of Naturalists

Society for Integrative and Comparative Biology

## **Working Groups**

Participant. 2016. Local-scale ecosystem resilience amid global-scale ocean change: the coral reef example. USGS Powell Center for Analysis and Synthesis. Fort Collins, CO.

# Professional Development

## **Research**

Ensembl Browser Workshop, Bioinformatics Core, University of California, Davis \hfill 2019

Comparative Genomics Course, Physalia Courses, Berlin, Germany \hfill 2018

RevBayes Workshop, Center for Population Biology, University of California, Davis \hfill 2018

## **Teaching**

Inclusive and Accurate Approaches for Teaching Sex and Gender in Biology, Project Biodiversify Workshop, UC Davis \hfill 2020

Fall Foundations in Teaching Workshop Series, UC Davis Center for Educational Effectiveness \hfill 2017

California STEM Symposium Attendee, Anaheim, CA \hfill 2015

## **Diversity & Inclusion** 

Diversity in STEM Conference Panelist & Attendee, UC Davis \hfill 2020

Mental Health Gatekeeper Training, UC Davis \hfill 2018

Diversity 102 Workshop, GradPathways, UC Davis Graduate Studies \hfill 2018

Foundations in LGBTQIA Allyship Training, UC Davis LGBTQIA Resource Center \hfill 2018

UndocuAlly Program for Educators, UC Davis AB540 and Undocumented Center \hfill 2017

Graduate Diversity Orientation Program Extension Workshops, UC Davis \hfill 2017-2018

# Outreach & Community Service

Organizer, Evolution & Ecology Graduate School Preview Series, UC Davis \hfill 2020

> https://eegradpreview.weebly.com/

Panelist, Graduate School Experience Panel, Diversity in STEM Conference, UC Davis \hfill 2020 

Volunteer station leader, Picnic Day, Evolution & Ecology Department, UC Davis \hfill 2019

Volunteer ambassador, Team Graduate School, UC Davis \hfill 2019

Coordinator/co-founder, STEM Squad, Winters Middle School, Winters, CA \hfill 2018-present

>  https://estemestemsquad.weebly.com/ 

Volunteer station leader, STEM Stars, Shirley Rominger Intermediate School, Winters, CA \hfill 2018-2019

Volunteer teaching assistant, Visualizing and Mapping Bioassessment Data in R, 25th Annual Meeting of California Aquatic Bioassessment Workgroup, UC Davis \hfill 2018

Volunteer facilitator, Creek Science Investigations, Putah Creek Council, Winters, CA \hfill 2018

Volunteer scientist, Family STEAM Night, John Barrett Middle School, Carmichael, CA \hfill 2017-2018

Coordinator/co-founder, Girls in Science & Technology Club, Portola Middle School, Tarzana, CA \hfill 2016

>  https://gistclub.weebly.com/ 

Volunteer presenter, Multnomah Elementary School Career Day, Los Angeles, CA \hfill 2016

Volunteer judge, Portola Middle School Highly Gifted Magnet Science Fair, Tarzana, CA \hfill 2016

Volunteer alumni interviewer, Brown University \hfill 2016

Guest lecturer, Viewpoint School, Calabasas, CA \hfill 2015-2016

Guest lecturer, Virgin Islands Environmental Resource Station, St. John, USVI \hfill 2014-2016

Mentor, Calabasas High School Marine Biology Club, Calabasas, CA \hfill 2014-2015

<!-- # Skills -->

<!-- \begin{tabbing} -->
<!-- \textit{Programming:} \= R (\textit{advanced}), Python (\textit{basic}), Java (\textit{basic}) \\ [1.5ex] -->
<!-- \textit{Software:} \> RevBayes, JMP, CPCe, ImageJ, GIS, Adobe Photoshop, Microsoft Office \\ [1.5ex] -->
<!-- \textit{Scuba Diving:} \> AAUS Scientific Diver (\textit{>500 scientific dives}), PADI Rescue Diver, CPR, O2, First Aid \\ [1.5ex] -->
<!-- \textit{Boating:} \> Washington State Boater Education Card, small motorboat operation \\ [1.5ex] -->
<!-- \end{tabbing} -->

